name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0, v2.3.1

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🔥 New release: ${{ github.ref_name }}

            ## Changelog
            - Added: Increment / Decrement / Reset counter
            - Theme: Light and Dark mode
            - Refactored for scalable structure
            - Responsive UI with ScreenUtil

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
